import React, {useState} from 'react'
import Head from 'next/head'
import Jumbotron from '../parts/Jumbotron'
import Pricing from '../parts/Pricing'
import Testimonial from '../parts/Testimonial'
import Navbar from "../components/Navbar";
import Contact from '../parts/Contact';
import Footer from '../parts/Footer';
import MobileMenu from '../components/MobileMenu';

export default function Home() {
  const [toggle, setToggle] = useState(false);
  const handleToggle = () => {
    setToggle(!toggle);
    console.log('clicked')
  }
  return (
    <div className='relative overflow-hidden'>
      <Head>
        <title>Ecodu.id - STAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-hero bg-opacity-25 bg-no-repeat bg-cover'>
        <Navbar handleToggle={handleToggle} />
        <Jumbotron />
      </div>
      <Pricing />
      <div className="my-16 py-20 bg-primary-color">
        <Testimonial />
      </div>
      <Contact />
      <div className="bg-additional-color-100 mt-32">
        <Footer />
      </div>
      <MobileMenu toggle={toggle} handleToggle={handleToggle} />
    </div>
  )
}
