import Head from 'next/head'
import Jumbotron from '../parts/Jumbotron'
import Pricing from '../parts/Pricing'
import Testimonial from '../parts/Testimonial'
import Navbar from "../components/Navbar";
import Contact from '../parts/Contact';
import Footer from '../parts/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ecodu.id - STAN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='bg-hero bg-opacity-25 bg-no-repeat bg-cover'>
          <Navbar />
          <Jumbotron />
        </div>
        <Pricing />
        <div className="my-16 py-20 bg-primary-color">
          <Testimonial />
        </div>
        <Contact />
        <div className="bg-additional-color-100 mt-32">
          <Footer />
        </div>
    </div>
  )
}
